### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by call-a3** [davidguttman/sassify#24]
@davidguttman Could you set up a [TravisCI](https://travis-ci.org) account for sassify? It's free for open source projects such as sassify.

Up till now I set one up to track my fork, but if I'm going to be contributing to the original project directly, I think it would be best if it had it's own CI set up. That way, I don't have to manually keep my own fork in sync with master just for the sake of testing ;)

**Comment by davidguttman** [comment]
Just set it up, let me know if you need me to do anything else, thanks!
