### ISSUE TITLE
Usage with `import * from` / `require`

### ISSUE THREAD

**Issue by oncletom** [davidguttman/sassify#32]
Hi there,

I wanted to do the following with ES6/Babelify + Sassify:

``` js
import document from 'globals/document';
import * as stylesheet from './stylesheet.scss';

const cssEl = document.createElement('style');
cssEl.type = 'text/css';
cssEl.innerHTML = stylesheet.toString();
document.head.appendChild(cssEl);
```

But for some reason I have an `[object Object]` instead of a CSS string (the content of the transpiled Sass code).

Is there any way to inject code on our own, without relying on `auto-inject` option?

Thanks.

**Comment by noahehall** [comment]
blah = Object {one: 1, three: Object}
blah.toString() >> "[object Object]"
JSON.stringify(blah) >> "{"one":1,"three":{"foure":2}}"

**Comment by nobitagit** [comment]
Actually what works for me is

```
import style from './style.scss';

const cssEl = document.createElement('style');
cssEl.type = 'text/css';
cssEl.innerHTML = style; 
document.head.appendChild(cssEl);
```
