### ISSUE TITLE
Any idea about the version tags?

### ISSUE THREAD

**Issue by philiptzou** [davidguttman/sassify#34]
It looks the most recent commit of sassify so far is in [v0.5.3](https://github.com/davidguttman/sassify/tree/v0.5.3). But the highest version (so far) is [v0.9.1](https://github.com/davidguttman/sassify/tree/v0.9.1). It's kinda weird. Is it a mistake or intentional?

**Comment by davidguttman** [comment]
Intentional, it was a fix for the `0.5.x` series. It doesn't affect the latest version(s).

**Comment by davidguttman** [comment]
Thanks for bringing this up!

It looks like there *was* a mistake, and npm serves `0.5.x` by default. Looking into it.

**Comment by davidguttman** [comment]
Ok, should be fixed now. Looks like I messed up the npm dist-tag by mistake and `0.5.3` was set as latest.

`npm install sassify` should do `0.9.1` now.

**Comment by philiptzou** [comment]
Thanks!
