### ISSUE TITLE
Boolean value default to false

### ISSUE THREAD

**Issue by xbtsw** [davidguttman/sassify#35]
Some of the boolean options defaulted to `true`. However due to browserify use `minimist` to parse the subargs, there's no way to overwrite a default `true` option to `false` in command line.

```
browserify -t [sassify --auto-inject --base64Encode] //base64Encode set to true, auto-inject set to true
browserify -t [sassify --auto-inject] //auto-inject set to true, but base64Encode still set to true
```

There's basically no way to set `base64Encode` to `false` in command line invocation as it defaults to `true`.

I think we should change the boolean options default to `false`. Please kindly comment. @davidguttman

**Comment by davidguttman** [comment]
Sorry for the delay on this -- slipped through.

I agree with that change.

**Comment by davidguttman** [comment]
In `v1.0.0`
