### ISSUE TITLE
Import from npm install files

### ISSUE THREAD

**Issue by konsumer** [davidguttman/sassify#37]
I would like to be able to import from other projects in node_modules at runtime, using my npm path. The problem is when I have a module installed alongside other modules that are it's dependencies (as with modern version of npm) and so I can't count on the structure of node_modules.

It would turn things like this:

```scss
@import "../../../node_modules/material-colors/dist/colors.scss";
```

which breaks if the module is installed alongside material-colors. The path that would work in that case, but not standalone, would look like this:

```scss
@import "../../../../material-colors/dist/colors.scss";
```

If there was even a way to count on the node_modules dir in a variable, and I could do something like this, it would work ok, even if not ideal:

```scss
@import $module_path + "material-colors/dist/colors.scss";
```

I'd prefer to be able to do something like this:

```scss
@import "material-colors/dist/colors.scss";
```
less/lessify works this way.

[This module](https://www.npmjs.com/package/sass-module-importer) gets close, but has requirements to setup package.json with the right structure. I made [an issue](https://github.com/lucasmotta/sass-module-importer/issues/17) that tracks that, so maybe it will be as simple as adding that module to the node-sass options.

**Comment by konsumer** [comment]
Actually [sass-module-importer](https://www.npmjs.com/package/sass-module-importer) appears to already do this, so I guess the issue is including that project in the options for node-sass, like this:

```js
var sass = require('node-sass');
var moduleImporter = require('sass-module-importer');

sass.render({
  file: './source/css/app.scss',
  importer: moduleImporter()
}, cb);
```

Do you want me to make a PR?

**Comment by davidguttman** [comment]
That would be great, thanks!

**Comment by konsumer** [comment]
Should I also increment the npm semver MINOR so you can easily `npm publish`?

**Comment by davidguttman** [comment]
Usually, I'd handle the versioning, but either way.

**Comment by konsumer** [comment]
Ah ok, sorry. I already did it on the PR, but you can just not merge that commit if you don;t like the version. Thanks!

**Comment by konsumer** [comment]
I was getting an error about importer being a function, so I moved it down to the `if (options.importer)` statement. I will do some more testing and make sure it works ok. This brings to light the issue that options.importer might not be a string, so maybe we should just pass it along without resolving path.

Old code:
```js
    if ((path.resolve(options.importer) === path.normalize(options.importer).replace(/(.+)([\/|\\])$/, '$1'))){
            options.importer = require(options.importer);
        } else {
            options.importer = require(path.resolve(options.importer));
        }
    }
```

Idea:

```js
    if (!options.importer) {
        options.importer = moduleImporter();
    }
```

**Comment by konsumer** [comment]
Seems to work fine with the first fix. [Here](https://gist.github.com/konsumer/8ae37251278fed4fad9dc3e815bca0eb) is a gist to try it out.
