### ISSUE TITLE
Sassify doesn't seem to do anything

### ISSUE THREAD

**Issue by peterbarraud** [davidguttman/sassify#43]
On the main page, you say `Currently breaks in some cases on node 0.11.x with latest version (2.0.1) of node-sass as documented in node-sass issue #550. This is also the reason why node 0.11 is currently not supported. Use at your own risk (though no actual risk is involved, it might just not work).`

I'm trying this with sassify@3.0.0. What am I supposed to do to get it to work. Any specific version?

**Comment by davidguttman** [comment]
Hey sorry about this, I haven't been paying enough attention to this project. We haven't used it for anything recent, and so our apps use older versions.

It looks like I accepted a PR that has the "standard" behavior disabled by default. I'm going to create a new version that reverses this.

**Comment by davidguttman** [comment]
Ok, should be working normally by default in `sassify@4.0.0`.

Sorry about that!
